@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.ironhack.bankApi.models.users.User",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_309686295 { 
   	label=ironhack
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2043467463 { 
   	label=bankApi
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Account1161819390[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Account</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   balance: Money [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   creationDate: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   penaltyFee: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   primaryOwner: AccountHolder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   secondaryOwner: AccountHolder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   secretKey: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: Status [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ decreaseBalance(decrease: BigDecimal)</TD></TR>
<TR><TD ALIGN="LEFT" >+ increaseBalance(increase: BigDecimal)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AccountHolder2054157420[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AccountHolder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dateOfBirth: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mailingAddress: Address [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mainAccountList: List&lt;Account&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   primaryAddress: Address [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   secondaryAccountList: List&lt;Account&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Address2054190869[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Address</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   city: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   number: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   postalCode: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   street: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Admin2054157420[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Admin</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CheckingAccount1161819390[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CheckingAccount</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   minimumBalance: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   monthlyMaintenanceFee: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ decreaseBalance(decrease: BigDecimal)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CreditCard1161819390[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CreditCard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   creditLimit: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   interestDate: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   interestRate: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addInterest()</TD></TR>
<TR><TD ALIGN="LEFT" >+ decreaseBalance(decrease: BigDecimal)</TD></TR>
<TR><TD ALIGN="LEFT" >+ increaseBalance(increase: BigDecimal)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CustomUserDetails392416728[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CustomUserDetails</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   user: User [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Money2054190869[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Money</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   amount: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currency: Currency [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ decreaseAmount(money: Money): BigDecimal</TD></TR>
<TR><TD ALIGN="LEFT" >+ decreaseAmount(addAmount: BigDecimal): BigDecimal</TD></TR>
<TR><TD ALIGN="LEFT" >+ increaseAmount(money: Money): BigDecimal</TD></TR>
<TR><TD ALIGN="LEFT" >+ increaseAmount(addAmount: BigDecimal): BigDecimal</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Role2054157420[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Role</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   role: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   roleUser: User [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Savings1161819390[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Savings</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   interestDate: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   interestRate: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   minimumBalance: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addInterest()</TD></TR>
<TR><TD ALIGN="LEFT" >+ decreaseBalance(decrease: BigDecimal)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

StudentCheckingAccount1161819390[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)StudentCheckingAccount</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TransferList2054190869[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TransferList</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   from: Account [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantity: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   to: Account [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

User2054157420[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)User</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   roles: List&lt;Role&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Account1161819390 -> AccountHolder2054157420[label="primaryOwner
[0..1]"];
Account1161819390 -> AccountHolder2054157420[label="secondaryOwner
[0..1]"];
Account1161819390 -> CheckingAccount1161819390[arrowhead=none, arrowtail=empty, dir=both];
Account1161819390 -> CreditCard1161819390[arrowhead=none, arrowtail=empty, dir=both];
Account1161819390 -> Money2054190869[label="balance
[0..1]"];
Account1161819390 -> Savings1161819390[arrowhead=none, arrowtail=empty, dir=both];
Account1161819390 -> StudentCheckingAccount1161819390[arrowhead=none, arrowtail=empty, dir=both];
AccountHolder2054157420 -> Account1161819390[label="mainAccountList
[0..*]"];
AccountHolder2054157420 -> Account1161819390[label="secondaryAccountList
[0..*]"];
AccountHolder2054157420 -> Address2054190869[label="mailingAddress
[0..1]"];
AccountHolder2054157420 -> Address2054190869[label="primaryAddress
[0..1]"];
CustomUserDetails392416728 -> User2054157420[label="user
[0..1]"];
Role2054157420 -> User2054157420[label="roleUser
[0..1]"];
TransferList2054190869 -> Account1161819390[label="from
[0..1]"];
TransferList2054190869 -> Account1161819390[label="to
[0..1]"];
User2054157420 -> AccountHolder2054157420[arrowhead=none, arrowtail=empty, dir=both];
User2054157420 -> Admin2054157420[arrowhead=none, arrowtail=empty, dir=both];
User2054157420 -> Role2054157420[label="roles
[0..*]"];
    
}
@enduml